version: '1.0'

services:
  bwtapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: bwtapp
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - bwtapp-network

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - bwtapp-network

networks:
  bwtapp-network:
